/*
  Warnings:

  - You are about to drop the `LoyaltyTransaction` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `WalletTransaction` table. If the table is not empty, all the data it contains will be lost.

*/
-- CreateEnum
CREATE TYPE "public"."OfferType" AS ENUM ('REGULAR_DISCOUNT', 'VOUCHER', 'COUNTDOWN_DEAL', 'FLASH_SALE', 'BUY_X_GET_Y', 'FREE_SHIPPING', 'BUNDLE_DEAL', 'SEASONAL_SALE', 'LOYALTY_REWARD', 'REFERRAL_BONUS');

-- CreateEnum
CREATE TYPE "public"."OfferCategoryType" AS ENUM ('GENERAL', 'ELECTRONICS', 'FASHION', 'HOME_GARDEN', 'BEAUTY', 'SPORTS', 'BOOKS', 'FOOD_BEVERAGE');

-- CreateEnum
CREATE TYPE "public"."DiscountType" AS ENUM ('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING', 'BUY_X_GET_Y');

-- CreateEnum
CREATE TYPE "public"."CreatorType" AS ENUM ('ADMIN', 'VENDOR', 'SYSTEM');

-- DropForeignKey
ALTER TABLE "public"."LoyaltyTransaction" DROP CONSTRAINT "LoyaltyTransaction_userId_fkey";

-- DropForeignKey
ALTER TABLE "public"."WalletTransaction" DROP CONSTRAINT "WalletTransaction_userId_fkey";

-- AlterTable
ALTER TABLE "public"."orders" ADD COLUMN     "appliedOfferId" TEXT,
ADD COLUMN     "discountAmount" DOUBLE PRECISION DEFAULT 0;

-- DropTable
DROP TABLE "public"."LoyaltyTransaction";

-- DropTable
DROP TABLE "public"."WalletTransaction";

-- CreateTable
CREATE TABLE "public"."offer_permissions" (
    "id" TEXT NOT NULL,
    "vendorId" TEXT NOT NULL,
    "canCreateRegular" BOOLEAN NOT NULL DEFAULT true,
    "canCreateVoucher" BOOLEAN NOT NULL DEFAULT true,
    "canCreateCountdown" BOOLEAN NOT NULL DEFAULT false,
    "canCreateFlashSale" BOOLEAN NOT NULL DEFAULT false,
    "maxActiveOffers" INTEGER NOT NULL DEFAULT 5,
    "maxDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 50,
    "maxDiscountAmount" DOUBLE PRECISION NOT NULL DEFAULT 1000,
    "requiresApproval" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "offer_permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offers" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "slug" TEXT NOT NULL,
    "type" "public"."OfferType" NOT NULL,
    "category" "public"."OfferCategoryType" NOT NULL DEFAULT 'GENERAL',
    "discountType" "public"."DiscountType" NOT NULL,
    "discountValue" DOUBLE PRECISION NOT NULL,
    "maxDiscountAmount" DOUBLE PRECISION,
    "minOrderAmount" DOUBLE PRECISION,
    "validFrom" TIMESTAMP(3) NOT NULL,
    "validTo" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "totalUsageLimit" INTEGER,
    "userUsageLimit" INTEGER,
    "currentUsageCount" INTEGER NOT NULL DEFAULT 0,
    "isPublic" BOOLEAN NOT NULL DEFAULT true,
    "applicableToAll" BOOLEAN NOT NULL DEFAULT true,
    "createdByType" "public"."CreatorType" NOT NULL,
    "createdByUserId" TEXT,
    "createdByVendorId" TEXT,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "bannerImage" TEXT,
    "termsAndConditions" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "offers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."countdown_offers" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "originalPrice" DOUBLE PRECISION,
    "flashPrice" DOUBLE PRECISION,
    "quantityLimit" INTEGER,
    "remainingQty" INTEGER,
    "countdownEnds" TIMESTAMP(3) NOT NULL,
    "showCountdown" BOOLEAN NOT NULL DEFAULT true,
    "urgencyText" TEXT,
    "scarcityText" TEXT,

    CONSTRAINT "countdown_offers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."voucher_offers" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "isPublic" BOOLEAN NOT NULL DEFAULT true,
    "requiresCode" BOOLEAN NOT NULL DEFAULT true,
    "firstTimeOnly" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "voucher_offers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_products" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,

    CONSTRAINT "offer_products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_categories" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,

    CONSTRAINT "offer_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_vendors" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "vendorId" TEXT NOT NULL,

    CONSTRAINT "offer_vendors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_users" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,

    CONSTRAINT "offer_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_usage" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "orderId" INTEGER,
    "discountApplied" DOUBLE PRECISION NOT NULL,
    "orderAmount" DOUBLE PRECISION NOT NULL,
    "usedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "offer_usage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."offer_analytics" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "totalViews" INTEGER NOT NULL DEFAULT 0,
    "totalClicks" INTEGER NOT NULL DEFAULT 0,
    "totalUsage" INTEGER NOT NULL DEFAULT 0,
    "totalRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "conversionRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "avgOrderValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "recordDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "offer_analytics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."wallet_transactions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "type" "public"."WalletTransactionType" NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wallet_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."loyalty_transactions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "points" INTEGER NOT NULL,
    "type" "public"."LoyaltyTransactionType" NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "loyalty_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "offer_permissions_vendorId_key" ON "public"."offer_permissions"("vendorId");

-- CreateIndex
CREATE UNIQUE INDEX "offers_slug_key" ON "public"."offers"("slug");

-- CreateIndex
CREATE INDEX "offers_type_isActive_validFrom_validTo_idx" ON "public"."offers"("type", "isActive", "validFrom", "validTo");

-- CreateIndex
CREATE INDEX "offers_createdByVendorId_isActive_idx" ON "public"."offers"("createdByVendorId", "isActive");

-- CreateIndex
CREATE INDEX "offers_validFrom_validTo_isActive_idx" ON "public"."offers"("validFrom", "validTo", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "countdown_offers_offerId_key" ON "public"."countdown_offers"("offerId");

-- CreateIndex
CREATE UNIQUE INDEX "voucher_offers_offerId_key" ON "public"."voucher_offers"("offerId");

-- CreateIndex
CREATE UNIQUE INDEX "voucher_offers_code_key" ON "public"."voucher_offers"("code");

-- CreateIndex
CREATE INDEX "voucher_offers_code_idx" ON "public"."voucher_offers"("code");

-- CreateIndex
CREATE UNIQUE INDEX "offer_products_offerId_productId_key" ON "public"."offer_products"("offerId", "productId");

-- CreateIndex
CREATE UNIQUE INDEX "offer_categories_offerId_categoryId_key" ON "public"."offer_categories"("offerId", "categoryId");

-- CreateIndex
CREATE UNIQUE INDEX "offer_vendors_offerId_vendorId_key" ON "public"."offer_vendors"("offerId", "vendorId");

-- CreateIndex
CREATE UNIQUE INDEX "offer_users_offerId_userId_key" ON "public"."offer_users"("offerId", "userId");

-- CreateIndex
CREATE INDEX "offer_usage_offerId_userId_idx" ON "public"."offer_usage"("offerId", "userId");

-- CreateIndex
CREATE INDEX "offer_usage_usedAt_idx" ON "public"."offer_usage"("usedAt");

-- CreateIndex
CREATE UNIQUE INDEX "offer_analytics_offerId_recordDate_key" ON "public"."offer_analytics"("offerId", "recordDate");

-- AddForeignKey
ALTER TABLE "public"."offer_permissions" ADD CONSTRAINT "offer_permissions_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "public"."vendors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offers" ADD CONSTRAINT "offers_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "public"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offers" ADD CONSTRAINT "offers_createdByVendorId_fkey" FOREIGN KEY ("createdByVendorId") REFERENCES "public"."vendors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."countdown_offers" ADD CONSTRAINT "countdown_offers_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."voucher_offers" ADD CONSTRAINT "voucher_offers_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_products" ADD CONSTRAINT "offer_products_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_products" ADD CONSTRAINT "offer_products_productId_fkey" FOREIGN KEY ("productId") REFERENCES "public"."products"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_categories" ADD CONSTRAINT "offer_categories_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_categories" ADD CONSTRAINT "offer_categories_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "public"."categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_vendors" ADD CONSTRAINT "offer_vendors_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_vendors" ADD CONSTRAINT "offer_vendors_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "public"."vendors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_users" ADD CONSTRAINT "offer_users_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_users" ADD CONSTRAINT "offer_users_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_usage" ADD CONSTRAINT "offer_usage_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_usage" ADD CONSTRAINT "offer_usage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_usage" ADD CONSTRAINT "offer_usage_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "public"."orders"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."offer_analytics" ADD CONSTRAINT "offer_analytics_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "public"."offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."wallet_transactions" ADD CONSTRAINT "wallet_transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."loyalty_transactions" ADD CONSTRAINT "loyalty_transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
